<?php

use Illuminate\Database\Seeder;

class DistrictsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement("INSERT INTO `districts` (`id`, `city_id`, `name`, `slug`, `order`) VALUES
            (1, 2, 'Quận Ba Đình', 'Quan-Ba-Dinh', 1),
            (2, 2, 'Quận Hoàn Kiếm', 'Quan-Hoan-Kiem', 2),
            (3, 2, 'Quận Hai Bà Trưng', 'Quan-Hai-Ba-Trung', 3),
            (4, 2, 'Quận Đống Đa', 'Quan-Dong-Da', 4),
            (5, 2, 'Quận Tây Hồ', 'Quan-Tay-Ho', 5),
            (6, 2, 'Quận Cầu Giấy', 'Quan-Cau-Giay', 6),
            (7, 2, 'Quận Thanh Xuân', 'Quan-Thanh-Xuan', 7),
            (8, 2, 'Quận Hoàng Mai', 'Quan-Hoang-Mai', 8),
            (9, 2, 'Quận Long Biên', 'Quan-Long-Bien', 9),
            (10, 2, 'Huyện Từ Liêm', 'Huyen-Tu-Liem', 10),
            (11, 2, 'Huyện Thanh Trì', 'Huyen-Thanh-Tri', 11),
            (12, 2, 'Huyện Gia Lâm', 'Huyen-Gia-Lam', 12),
            (13, 2, 'Huyện Đông Anh', 'Huyen-Dong-Anh', 13),
            (14, 2, 'Huyện Sóc Sơn', 'Huyen-Soc-Son', 14),
            (15, 2, 'Thành phố Hà Đông', 'Thanh-pho-Ha-Dong', 15),
            (16, 2, 'Thành phố Sơn Tây', 'Thanh-pho-Son-Tay', 16),
            (17, 2, 'Huyện Ba Vì', 'Huyen-Ba-Vi', 17),
            (18, 2, 'Huyện Phúc Thọ', 'Huyen-Phuc-Tho', 18),
            (19, 2, 'Huyện Thạch Thất', 'Huyen-Thach-That', 19),
            (20, 2, 'Huyện Quốc Oai', 'Huyen-Quoc-Oai', 20),
            (21, 2, 'Huyện Chương Mỹ', 'Huyen-Chuong-My', 21),
            (22, 2, 'Huyện Đan Phượng', 'Huyen-Dan-Phuong', 22),
            (23, 2, 'Huyện Hoài Đức', 'Huyen-Hoai-Duc', 23),
            (24, 2, 'Huyện Thanh Oai', 'Huyen-Thanh-Oai', 24),
            (25, 2, 'Huyện Mỹ Đức', 'Huyen-My-Duc', 25),
            (26, 2, 'Huyện Ứng Hòa', 'Huyen-Ung-Hoa', 26),
            (27, 2, 'Huyện Thường Tín', 'Huyen-Thuong-Tin', 27),
            (28, 2, 'Huyện Phú Xuyên', 'Huyen-Phu-Xuyen', 28),
            (29, 2, 'Huyện Mê Linh', 'Huyen-Me-Linh', 29),
            (30, 1, 'Quận Một', 'Quan-Mot', 1),
            (31, 1, 'Quận Hai', 'Quan-Hai', 2),
            (32, 1, 'Quận Ba', 'Quan-Ba', 3),
            (33, 1, 'Quận Bốn', 'Quan-Bon', 4),
            (34, 1, 'Quận Năm', 'Quan-Nam', 5),
            (35, 1, 'Quận Sáu', 'Quan-Sau', 6),
            (36, 1, 'Quận Bảy', 'Quan-Bay', 7),
            (37, 1, 'Quận Tám', 'Quan-Tam', 8),
            (38, 1, 'Quận Chín', 'Quan-Chin', 9),
            (39, 1, 'Quận Mười', 'Quan-Muoi', 10),
            (40, 1, 'Quận Mười một', 'Quan-Muoi-mot', 11),
            (41, 1, 'Quận Mười hai', 'Quan-Muoi-hai', 12),
            (42, 1, 'Quận Gò Vấp', 'Quan-Go-Vap', 13),
            (43, 1, 'Quận Tân Bình', 'Quan-Tan-Binh', 14),
            (44, 1, 'Quận Tân Phú', 'Quan-Tan-Phu', 15),
            (45, 1, 'Quận Bình Thạnh', 'Quan-Binh-Thanh', 16),
            (46, 1, 'Quận Phú Nhuận', 'Quan-Phu-Nhuan', 17),
            (47, 1, 'Quận Thủ Đức', 'Quan-Thu-Duc', 18),
            (48, 1, 'Quận Bình Tân', 'Quan-Binh-Tan', 19),
            (49, 1, 'Huyện Bình Chánh', 'Huyen-Binh-Chanh', 20),
            (50, 1, 'Huyện Củ Chi', 'Huyen-Cu-Chi', 21),
            (51, 1, 'Huyện Hóc Môn', 'Huyen-Hoc-Mon', 22),
            (52, 1, 'Huyện Nhà Bè', 'Huyen-Nha-Be', 23),
            (53, 1, 'Huyện Cần Giờ', 'Huyen-Can-Gio', 24),
            (55, 28, 'Quận Hồng Bàng', 'Quan-Hong-Bang', 1),
            (56, 28, 'Quận Lê Chân', 'Quan-Le-Chan', 2),
            (57, 28, 'Quận Ngô Quyền', 'Quan-Ngo-Quyen', 3),
            (58, 28, 'Quận Kiến An', 'Quan-Kien-An', 4),
            (59, 28, 'Quận Hải An', 'Quan-Hai-An', 5),
            (60, 28, 'Quận Đồ Sơn', 'Quan-Do-Son', 6),
            (61, 28, 'Huyện An Lão', 'Huyen-An-Lao', 7),
            (62, 28, 'Huyện Kiến Thụy', 'Huyen-Kien-Thuy', 8),
            (63, 28, 'Huyện Thủy Nguyên', 'Huyen-Thuy-Nguyen', 9),
            (64, 28, 'Huyện An Dương', 'Huyen-An-Duong', 10),
            (65, 28, 'Huyện Tiên Lãng', 'Huyen-Tien-Lang', 11),
            (66, 28, 'Huyện Vĩnh Bảo', 'Huyen-Vinh-Bao', 12),
            (67, 28, 'Huyện Cát Hải', 'Huyen-Cat-Hai', 13),
            (68, 28, 'Huyện Bạch Long Vĩ', 'Huyen-Bach-Long-Vi', 14),
            (69, 28, 'Quận Dương Kinh', 'Quan-Duong-Kinh', 15),
            (70, 17, 'Quận Hải Châu', 'Quan-Hai-Chau', 1),
            (71, 17, 'Quận Thanh Khê', 'Quan-Thanh-Khe', 2),
            (72, 17, 'Quận Sơn Trà', 'Quan-Son-Tra', 3),
            (73, 17, 'Quận Ngũ Hành Sơn', 'Quan-Ngu-Hanh-Son', 4),
            (74, 17, 'Quận Liên Chiểu', 'Quan-Lien-Chieu', 5),
            (75, 17, 'Huyện Hoà Vang', 'Huyen-Hoa-Vang', 6),
            (76, 17, 'Quận Cẩm Lệ', 'Quan-Cam-Le', 7),
            (77, 24, 'Thị xã Hà Giang', 'Thi-xa-Ha-Giang', 1),
            (78, 24, 'Huyện Đồng Văn', 'Huyen-Dong-Van', 2),
            (79, 24, 'Huyện Mèo Vạc', 'Huyen-Meo-Vac', 3),
            (80, 24, 'Huyện Yên Minh', 'Huyen-Yen-Minh', 4),
            (81, 24, 'Huyện Quản Bạ', 'Huyen-Quan-Ba', 5),
            (82, 24, 'Huyện Vị Xuyên', 'Huyen-Vi-Xuyen', 6),
            (83, 24, 'Huyện Bắc Mê', 'Huyen-Bac-Me', 7),
            (84, 24, 'Huyện Hoàng Su Phì', 'Huyen-Hoang-Su-Phi', 8),
            (85, 24, 'Huyện Xín Mần', 'Huyen-Xin-Man', 9),
            (86, 24, 'Huyện Bắc Quang', 'Huyen-Bac-Quang', 10),
            (87, 24, 'Huyện Quang Bình', 'Huyen-Quang-Binh', 11),
            (88, 16, 'Thị xã Cao Bằng', 'Thi-xa-Cao-Bang', 1),
            (89, 16, 'Huyện Bảo Lạc', 'Huyen-Bao-Lac', 2),
            (90, 16, 'Huyện Thông Nông', 'Huyen-Thong-Nong', 3),
            (91, 16, 'Huyện Hà Quảng', 'Huyen-Ha-Quang', 4),
            (92, 16, 'Huyện Trà Lĩnh', 'Huyen-Tra-Linh', 5),
            (93, 16, 'Huyện Trùng Khánh', 'Huyen-Trung-Khanh', 6),
            (94, 16, 'Huyện Nguyên Bình', 'Huyen-Nguyen-Binh', 7),
            (95, 16, 'Huyện Hoà An', 'Huyen-Hoa-An', 8),
            (96, 16, 'Huyện Quảng Uyên', 'Huyen-Quang-Uyen', 9),
            (97, 16, 'Huyện Thạch An', 'Huyện Thạch An', 10),
            (98, 16, 'Huyện Hạ Lang', 'Huyện Hạ Lang', 11),
            (99, 16, 'Huyện Bảo Lâm', 'Huyện Bảo Lâm', 12),
            (100, 16, 'Huyện Phục Hoà', 'Huyện Phục Hoà', 13),
            (101, 35, 'Thị xã Lai Châu', 'Thi-xa-Lai-Chau', 1),
            (102, 35, 'Huyện Tam Đường', 'Huyen-Tam-Duong', 2),
            (103, 35, 'Huyện Phong Thổ', 'Huyen-Phong-Tho', 3),
            (104, 35, 'Huyện Sìn Hồ', 'Huyen-Sin-Ho', 4),
            (105, 35, 'Huyện Mường Tè', 'Huyen-Muong-Te', 5),
            (106, 35, 'Huyện Than Uyên', 'Huyen-Than-Uyen', 6),
            (107, 35, 'Huyện Tân Uyên', 'Huyen-Tan-Uyen', 7),
            (108, 38, 'Thành phố Lào Cai', 'Thanh-pho-Lao-Cai', 1),
            (109, 38, 'Huyện Xi Ma Cai', 'Huyen-Xi-Ma-Cai', 2),
            (110, 38, 'Huyện Bát Xát', 'Huyen-Bat-Xat', 3),
            (111, 38, 'Huyện Bảo Thắng', 'Huyen-Bao-Thang', 4),
            (112, 38, 'Huyện Sa Pa', 'Huyen-Sa-Pa', 5),
            (113, 38, 'Huyện Văn Bàn', 'Huyen-Van-Ban', 6),
            (114, 38, 'Huyện Bảo Yên', 'Huyen-Bao-Yen', 7),
            (115, 38, 'Huyện Bắc Hà', 'Huyen-Bac-Ha', 8),
            (116, 38, 'Huyện Mường Khương', 'Huyen-Muong-Khuong', 9),
            (117, 60, 'Thị xã Tuyên Quang', 'Thi-xa-Tuyen-Quang', 1),
            (118, 60, 'Huyện Na Hang', 'Huyen-Na-Hang', 11),
            (119, 60, 'Huyện Chiêm Hoá', 'Huyen-Chiem-Hoa', 12),
            (120, 60, 'Huyện Hàm Yên', 'Huyen-Ham-Yen', 13),
            (121, 60, 'Huyện Yên Sơn', 'Huyen-Yen-Son', 14),
            (122, 60, 'Huyện Sơn Dương', 'Huyen-Son-Duong', 15),
            (123, 37, 'Thành phố Lạng Sơn', 'Thanh-pho-Lang-Son', 1),
            (124, 37, 'Huyện Văn Lãng', 'Huyen-Van-Lang', 2),
            (125, 37, 'Huyện Bắc Sơn', 'Huyen-Bac-Son', 3),
            (126, 37, 'Huyện Lộc Bình', 'Huyen-Loc-Binh', 4),
            (127, 37, 'Huyện Chi Lăng', 'Huyen-Chi-Lang', 5),
            (128, 37, 'Huyện Tràng Định', 'Huyen-Trang-Dinh', 6),
            (129, 37, 'Huyện Bình Gia', 'Huyen-Binh-Gia', 7),
            (130, 37, 'Huyện Văn Quan', 'Huyen-Van-Quan', 8),
            (131, 37, 'Huyện Cao Lộc', 'Huyen-Cao-Loc', 9),
            (132, 37, 'Huyện Đình Lập', 'Huyen-Dinh-Lap', 10),
            (133, 37, 'Huyện Hữu Lũng', 'Huyen-Huu-Lung', 11),
            (134, 3, 'TP.Long Xuyên', 'TPLong-Xuyen', 1),
            (135, 3, 'Thị xã Châu Đốc', 'Thi-xa-Chau-Doc', 2),
            (136, 3, 'Huyện An Phú', 'Huyen-An-Phu', 3),
            (137, 3, 'Huyện Tân Châu', 'Huyen-Tan-Chau', 4),
            (138, 3, 'Huyện Phú Tân', 'Huyen-Phu-Tan', 5),
            (139, 3, 'Huyện Tịnh Biên', 'Huyen-Tinh-Bien', 6),
            (140, 3, 'Huyện Tri Tôn', 'Huyen-Tri-Ton', 7),
            (141, 3, 'Huyện Châu Phú', 'Huyen-Chau-Phu', 8),
            (142, 3, 'Huyện Chợ Mới', 'Huyen-Cho-Moi', 9),
            (143, 3, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 10),
            (144, 3, 'Huyện Thoại Sơn', 'Huyen-Thoai-Son', 11),
            (145, 4, 'Thành phố Vũng Tàu', 'Thanh-pho-Vung-Tau', 1),
            (146, 4, 'Thị xã Bà Rịa', 'Thi-xa-Ba-Ria', 2),
            (147, 4, 'Huyện Xuyên Mộc', 'Huyen-Xuyen-Moc', 3),
            (148, 4, 'Huyện Long Điền', 'Huyen-Long-Dien', 4),
            (149, 4, 'Huyện Côn Đảo', 'Huyen-Con-Dao', 5),
            (150, 4, 'Huyện Tân Thành', 'Huyen-Tan-Thanh', 6),
            (151, 4, 'Huyện Châu Đức', 'Huyen-Chau-Duc', 7),
            (152, 4, 'Huyện Đất Đỏ', 'Huyen-Dat-Do', 8),
            (153, 58, 'Thành phố Mỹ Tho', 'Thanh-pho-My-Tho', 1),
            (154, 58, 'Thị xã Gò Công', 'Thi-xa-Go-Cong', 2),
            (155, 58, 'Huyện Cái Bè', 'Huyen-Cai-Be', 3),
            (156, 58, 'Huyện Cai Lậy', 'Huyen-Cai-Lay', 4),
            (157, 58, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 5),
            (158, 58, 'Huyện Chợ Gạo', 'Huyen-Cho-Gao', 6),
            (159, 58, 'Huyện Gò Công Tây', 'Huyen-Go-Cong-Tay', 7),
            (160, 58, 'Huyện Gò Công Đông', 'Huyen-Go-Cong-Dong', 8),
            (161, 58, 'Huyện Tân Phước', 'Huyen-Tan-Phuoc', 9),
            (162, 58, 'Huyện Tân Phú Đông', 'Huyen-Tan-Phu-Dong', 10),
            (163, 33, 'Thành phố Rạch Giá', 'Thanh-pho-Rach-Gia', 1),
            (164, 33, 'Thị xã Hà Tiên', 'Thi-xa-Ha-Tien', 2),
            (165, 33, 'Huyện Kiên Lương', 'Huyen-Kien-Luong', 3),
            (166, 33, 'Huyện Hòn Đất', 'Huyen-Hon-Dat', 4),
            (167, 33, 'Huyện Tân Hiệp', 'Huyen-Tan-Hiep', 5),
            (168, 33, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 6),
            (169, 33, 'Huyện Giồng Riềng', 'Huyen-Giong-Rieng', 7),
            (170, 33, 'Huyện Gò Quao', 'Huyen-Go-Quao', 8),
            (171, 33, 'Huyện An Biên', 'Huyen-An-Bien', 9),
            (172, 33, 'Huyện An Minh', 'Huyen-An-Minh', 10),
            (173, 33, 'Huyện Vĩnh Thuận', 'Huyen-Vinh-Thuan', 11),
            (174, 33, 'Huyện Phú Quốc', 'Huyen-Phu-Quoc', 12),
            (175, 33, 'Huyện Kiên Hải', 'Huyen-Kien-Hai', 13),
            (176, 33, 'Huyện U minh Thượng', 'Huyen-U-minh-Thuong', 14),
            (177, 15, 'Quận Ninh Kiều', 'Quan-Ninh-Kieu', 1),
            (178, 15, 'Quận Bình Thuỷ', 'Quan-Binh-Thuy', 2),
            (179, 15, 'Quận Cái Răng', 'Quan-Cai-Rang', 3),
            (180, 15, 'Quận Ô Môn', 'Quan-O-Mon', 4),
            (181, 15, 'Huyện Phong Điền', 'Huyen-Phong-Dien', 5),
            (182, 15, 'Huyện Cờ Đỏ', 'Huyen-Co-Do', 6),
            (183, 15, 'Huyện Vĩnh Thạnh', 'Huyen-Vinh-Thanh', 7),
            (184, 15, 'Huỵện Thốt Nốt', 'Huyen-Thot-Not', 8),
            (185, 9, 'Thị xã Bến Tre', 'Thi-xa-Ben-Tre', 1),
            (186, 9, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 2),
            (187, 9, 'Huyện Chợ Lách', 'Huyen-Cho-Lach', 3),
            (188, 9, 'Huyện Mỏ Cày', 'Huyen-Mo-Cay', 4),
            (189, 9, 'Huyện Giồng Trôm', 'Huyen-Giong-Trom', 5),
            (190, 9, 'Huyện Bình Đại', 'Huyen-Binh-Dai', 6),
            (191, 9, 'Huyện Ba Tri', 'Huyen-Ba-Tri', 7),
            (192, 9, 'Huyện Thạnh Phú', 'Huyen-Thanh-Phu', 8),
            (193, 61, 'Thị xã Vĩnh Long', 'Thi-xa-Vinh-Long', 1),
            (194, 61, 'Huyện Long Hồ', 'Huyen-Long-Ho', 2),
            (195, 61, 'Huyện Mang Thít', 'Huyen-Mang-Thit', 3),
            (196, 61, 'Huyện Bình Minh', 'Huyen-Binh-Minh', 4),
            (197, 61, 'Huyện Tam Bình', 'Huyen-Tam-Binh', 5),
            (198, 61, 'Huyện Trà Ôn', 'Huyen-Tra-On', 6),
            (199, 61, 'Huyện Vũng Liêm', 'Huyen-Vung-Liem', 7),
            (200, 61, 'Huyện Bình Tân', 'Huyen-Binh-Tan', 8),
            (201, 59, 'Thị xã Trà Vinh', 'Thi-xa-Tra-Vinh', 1),
            (202, 59, 'Huyện Càng Long', 'Huyen-Cang-Long', 2),
            (203, 59, 'Huyện Cầu Kè', 'Huyen-Cau-Ke', 3),
            (204, 59, 'Huyện Tiểu Cần', 'Huyen-Tieu-Can', 4),
            (205, 59, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 5),
            (206, 59, 'Huyện Trà Cú', 'Huyen-Tra-Cu', 6),
            (207, 59, 'Huyện Cầu Ngang', 'Huyen-Cau-Ngang', 7),
            (208, 59, 'Huyện Duyên Hải', 'Huyen-Duyen-Hai', 8),
            (209, 51, 'Thành phố Sóc Trăng', 'Thanh-pho-Soc-Trang', 1),
            (210, 51, 'Huyện Kế Sách', 'Huyen-Ke-Sach', 2),
            (211, 51, 'Huyện Mỹ Tú', 'Huyen-My-Tu', 3),
            (212, 51, 'Huyện Mỹ Xuyên', 'Huyen-My-Xuyen', 4),
            (213, 51, 'Huyện Thạnh Trị', 'Huyen-Thanh-Tri', 5),
            (214, 51, 'Huyện Long Phú', 'Huyen-Long-Phu', 6),
            (215, 51, 'Huyện Vĩnh Châu', 'Huyen-Vinh-Chau', 7),
            (216, 51, 'Huyện Cù Lao Dung', 'Huyen-Cu-Lao-Dung', 8),
            (217, 51, 'Huyện Ngã Năm', 'Huyen-Nga-Nam', 9),
            (218, 51, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 10),
            (219, 7, 'Thị xã Bạc Liêu', 'Thi-xa-Bac-Lieu', 1),
            (220, 7, 'Huyện Vĩnh Lợi', 'Huyen-Vinh-Loi', 2),
            (221, 7, 'Huyện Hồng Dân', 'Huyen-Hong-Dan', 3),
            (222, 7, 'Huyện Giá Rai', 'Huyen-Gia-Rai', 4),
            (223, 7, 'Huyện Phước Long', 'Huyen-Phuoc-Long', 5),
            (224, 7, 'Huyện Đông Hải', 'Huyen-Dong-Hai', 6),
            (225, 7, 'Huyện Hoà Bình', 'Huyen-Hoa-Binh', 7),
            (226, 14, 'Thành phố Cà Mau', 'Thanh-pho-Ca-Mau', 1),
            (227, 14, 'Huyện Thới Bình', 'Huyen-Thoi-Binh', 2),
            (228, 14, 'Huyện U Minh', 'Huyen-U-Minh', 3),
            (229, 14, 'Huyện Trần Văn Thời', 'Huyen-Tran-Van-Thoi', 4),
            (230, 14, 'Huyện Cái Nước', 'Huyen-Cai-Nuoc', 5),
            (231, 14, 'Huyện Đầm Dơi', 'Huyen-Dam-Doi', 6),
            (232, 14, 'Huyện Ngọc Hiển', 'Huyen-Ngoc-Hien', 7),
            (233, 14, 'Huyện Năm Căn', 'Huyen-Nam-Can', 8),
            (234, 14, 'Huyện Phú Tân', 'Huyen-Phu-Tan', 9),
            (235, 20, 'TP. Điện Biên Phủ', 'TP-Dien-Bien-Phu', 1),
            (236, 20, 'Thị xã Mường Lay', 'Thi-xa-Muong-Lay', 2),
            (237, 20, 'Huyện Điện Biên', 'Huyen-Dien-Bien', 3),
            (238, 20, 'Huyện Tuần Giáo', 'Huyen-Tuan-Giao', 4),
            (239, 20, 'Huyện Mường Chà', 'Huyen-Muong-Cha', 5),
            (240, 20, 'Huyện Tủa Chùa', 'Huyen-Tua-Chua', 6),
            (241, 20, 'Huyện Điện Biên Đông', 'Huyen-Dien-Bien-Dong', 7),
            (242, 20, 'Huyện Mường Nhé', 'Huyen-Muong-Nhe', 8),
            (243, 20, 'Huyện Mường Ảng', 'Huyen-Muong-Ang', 9),
            (244, 19, 'Thị xã Gia Nghĩa', 'Thi-xa-Gia-Nghia', 1),
            (245, 19, 'Huyện Dăk RLấp', 'Huyen-Dak-RLap', 2),
            (246, 19, 'Huyện Dăk Mil', 'Huyen-Dak-Mil', 3),
            (247, 19, 'Huyện Cư Jút', 'Huyen-Cu-Jut', 4),
            (248, 19, 'Huyện Dăk Song', 'Huyen-Dak-Song', 5),
            (249, 19, 'Huyện Krông Nô', 'Huyen-Krong-No', 6),
            (250, 19, 'Huyện Dăk GLong', 'Huyen-Dak-GLong', 7),
            (251, 19, 'Huyện Tuy Đức', 'Huyen-Tuy-Duc', 8),
            (252, 29, 'Thị xã Vị Thanh', 'Thi-xa-Vi-Thanh', 1),
            (253, 29, 'Huyện Vị Thuỷ', 'Huyen-Vi-Thuy', 2),
            (254, 29, 'Huyện Long Mỹ', 'Huyen-Long-My', 3),
            (255, 29, 'Huyện Phụng Hiệp', 'Huyen-Phung-Hiep', 4),
            (256, 29, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 5),
            (257, 29, 'Huyện Châu Thành A', 'Huyen-Chau-Thanh-A', 6),
            (258, 29, 'Thị xã Ngã Bảy', 'Thi-xa-Nga-Bay', 7),
            (259, 5, 'Thị xã Bắc Kạn', 'Thi-xa-Bac-Kan', 1),
            (260, 5, 'Huyện Chợ Đồn', 'Huyen-Cho-Don', 2),
            (261, 5, 'Huyện Bạch Thông', 'Huyen-Bach-Thong', 3),
            (262, 5, 'Huyện Na Rì', 'Huyen-Na-Ri', 4),
            (263, 5, 'Huyện Ngân Sơn', 'Huyen-Ngan-Son', 5),
            (264, 5, 'Huyện Ba Bể', 'Huyen-Ba-Be', 6),
            (265, 5, 'Huyện Chợ Mới', 'Huyen-Cho-Moi', 7),
            (266, 5, 'Huyện Pác Nặm', 'Huyen-Pac-Nam', 8),
            (267, 55, 'TP. Thái Nguyên', 'TP-Thai-Nguyen', 1),
            (268, 55, 'Thị xã Sông Công', 'Thi-xa-Song-Cong', 2),
            (269, 55, 'Huyện Định Hoá', 'Huyen-Dinh-Hoa', 3),
            (270, 55, 'Huyện Phú Lương', 'Huyen-Phu-Luong', 4),
            (271, 55, 'Huyện Võ Nhai&#039;', 'Huyen-Vo-Nhai', 5),
            (272, 55, 'Huyện Đại Từ', 'Huyen-Dai-Tu', 6),
            (273, 55, 'Huyện Đồng Hỷ', 'Huyen-Dong-Hy', 7),
            (274, 55, 'Huyện Phú Bình', 'Huyen-Phu-Binh', 8),
            (275, 55, 'Huyện Phổ Yên', 'Huyen-Pho-Yen', 9),
            (276, 63, 'Thành phố Yên Bái', 'Thanh-pho-Yen-Bai', 1),
            (277, 63, 'Thị xã Nghĩa Lộ', 'Thi-xa-Nghia-Lo', 2),
            (278, 63, 'Huyện Văn Yên', 'Huyen-Van-Yen', 3),
            (279, 63, 'Huyện Yên Bình', 'Huyen-Yen-Binh', 4),
            (280, 63, 'Huyện Mù Cang Chải', 'Huyen-Mu-Cang-Chai', 5),
            (281, 63, 'Huyện Văn Chấn', 'Huyen-Van-Chan', 6),
            (282, 63, 'Huyện Trấn Yên', 'Huyen-Tran-Yen', 7),
            (283, 63, 'Huyện Trạm Tấu', 'Huyen-Tram-Tau', 8),
            (284, 63, 'Huyện Lục Yên', 'Huyen-Luc-Yen', 9),
            (285, 52, 'Thị xã Sơn La', 'Thi-xa-Son-La', 1),
            (286, 52, 'Huyện Quỳnh Nhai', 'Huyen-Quynh-Nhai', 2),
            (287, 52, 'Huyện Mường La', 'Huyen-Muong-La', 3),
            (288, 52, 'Huyện Thuận Châu', 'Huyen-Thuan-Chau', 4),
            (289, 52, 'Huyện Bắc Yên', 'Huyen-Bac-Yen', 5),
            (290, 52, 'Huyện Phù Yên', 'Huyen-Phu-Yen', 6),
            (291, 52, 'Huyện Mai Sơn', 'Huyen-Mai-Son', 7),
            (292, 52, 'Huyện Yên Châu', 'Huyen-Yen-Chau', 8),
            (293, 52, 'Huyện Sông Mã', 'Huyen-Song-Ma', 9),
            (294, 52, 'Huyện Mộc Châu', 'Huyen-Moc-Chau', 10),
            (295, 52, 'Huyện Sốp Cộp', 'Huyen-Sop-Cop', 11),
            (296, 44, 'TP. Việt Trì', 'TP-Viet-Tri', 1),
            (297, 44, 'Thị xã Phú Thọ', 'Thi-xa-Phu-Tho', 2),
            (298, 44, 'Huyện Đoan Hùng', 'Huyen-Doan-Hung', 3),
            (299, 44, 'Huyện Thanh Ba', 'Huyen-Thanh-Ba', 4),
            (300, 44, 'Huyện Hạ Hoà', 'Huyen-Ha-Hoa', 5),
            (301, 44, 'Huyện Cẩm Khê', 'Huyen-Cam-Khe', 6),
            (302, 44, 'Huyện Yên Lập', 'Huyen-Yen-Lap', 7),
            (303, 44, 'Huyện Thanh Sơn', 'Huyen-Thanh-Son', 8),
            (304, 44, 'Huyện Phù Ninh', 'Huyen-Phu-Ninh', 9),
            (305, 44, 'Huyện Lâm Thao', 'Huyen-Lam-Thao', 10),
            (306, 44, 'Huyện Tam Nông', 'Huyen-Tam-Nong', 11),
            (307, 44, 'Huyện Thanh Thủy', 'Huyen-Thanh-Thuy', 12),
            (308, 44, 'Huyện Tân Sơn', 'Huyen-Tan-Son', 13),
            (309, 62, 'Thành phố Vĩnh Yên', 'Thanh-pho-Vinh-Yen', 1),
            (310, 62, 'Huyện Tam Dương', 'Huyen-Tam-Duong', 2),
            (311, 62, 'Huyện Lập Thạch', 'Huyen-Lap-Thach', 3),
            (312, 62, 'Huyện Vĩnh Tường', 'Huyen-Vinh-Tuong', 4),
            (313, 62, 'Huyện Yên Lạc', 'Huyen-Yen-Lac', 5),
            (314, 62, 'Huyện Bình Xuyên', 'Huyen-Binh-Xuyen', 6),
            (315, 62, 'Thị xã Phúc Yên', 'Thi-xa-Phuc-Yen', 7),
            (316, 62, 'Huyện Tam Đảo', 'Huyen-Tam-Dao', 8),
            (317, 49, 'TP. Hạ Long', 'TP-Ha-Long', 1),
            (318, 49, 'Thị xã Cẩm Phả', 'Thi-xa-Cam-Pha', 2),
            (319, 49, 'Thị xã Uông Bí', 'Thi-xa-Uong-Bi', 3),
            (320, 49, 'Thị xã Móng Cái', 'Thi-xa-Mong-Cai', 4),
            (321, 49, 'Huyện Bình Liêu', 'Huyen-Binh-Lieu', 5),
            (322, 49, 'Huyện Đầm Hà', 'Huyen-Dam-Ha', 6),
            (323, 49, 'Huyện Hải Hà', 'Huyen-Hai-Ha', 7),
            (324, 49, 'Huyện Tiên Yên', 'Huyen-Tien-Yen', 8),
            (325, 49, 'Huyện Ba Chẽ', 'Huyen-Ba-Che', 9),
            (326, 49, 'Huyện Đông Triều', 'Huyen-Dong-Trieu', 10),
            (327, 49, 'Huyện Yên Hưng', 'Huyen-Yen-Hung', 11),
            (328, 49, 'Huyện Hoành Bồ', 'Huyen-Hoanh-Bo', 12),
            (329, 49, 'Huyện Vân Đồn', 'Huyen-Van-Don', 13),
            (330, 49, 'Huyện Cô Tô', 'Huyen-Co-To', 14),
            (331, 6, 'Thành phố Bắc Giang', 'Thanh-pho-Bac-Giang', 1),
            (332, 6, 'Huyện Yên Thế', 'Huyen-Yen-The', 2),
            (333, 6, 'Huyện Lục Ngạn', 'Huyen-Luc-Ngan', 3),
            (334, 6, 'Huyện Sơn Động', 'Huyen-Son-Dong', 4),
            (335, 6, 'Huyện Lục Nam', 'Huyen-Luc-Nam', 5),
            (336, 6, 'Huyện Tân Yên', 'Huyen-Tan-Yen', 6),
            (337, 6, 'Huyện Hiệp Hoà', 'Huyen-Hiep-Hoa', 7),
            (338, 6, 'Huyện Lạng Giang', 'Huyen-Lang-Giang', 8),
            (339, 6, 'Huyện Việt Yên', 'Huyen-Viet-Yen', 9),
            (340, 6, 'Huyện Yên Dũng', 'Huyen-Yen-Dung', 10),
            (341, 8, 'Thành phố Bắc Ninh', 'Thanh-pho-Bac-Ninh', 1),
            (342, 8, 'Huyện Yên Phong', 'Huyen-Yen-Phong', 2),
            (343, 8, 'Huyện Quế Võ', 'Huyen-Que-Vo', 3),
            (344, 8, 'Huyện Tiên Du', 'Huyen-Tien-Du', 4),
            (345, 8, 'Huyện Từ Sơn', 'Huyen-Tu-Son', 5),
            (346, 8, 'Huyện Thuận Thành', 'Huyen-Thuan-Thanh', 6),
            (347, 8, 'Huyện Gia Bình', 'Huyen-Gia-Binh', 7),
            (348, 8, 'Huyện Lương Tài', 'Huyen-Luong-Tai', 8),
            (349, 27, 'Thành phố Hải Dương', 'Thanh-pho-Hai-Duong', 1),
            (350, 27, 'Huyện Chí Linh', 'Huyen-Chi-Linh', 2),
            (351, 27, 'Huyện Nam Sách', 'Huyen-Nam-Sach', 3),
            (352, 27, 'Huyện Kinh Môn', 'Huyen-Kinh-Mon', 4),
            (353, 27, 'Huyện Gia Lộc', 'Huyen-Gia-Loc', 5),
            (354, 27, 'Huyện Tứ Kỳ', 'Huyen-Tu-Ky', 6),
            (355, 27, 'Huyện Thanh Miện', 'Huyen-Thanh-Mien', 7),
            (356, 27, 'Huyện Ninh Giang', 'Huyen-Ninh-Giang', 8),
            (357, 27, 'Huyện Cẩm Giàng', 'Huyen-Cam-Giang', 9),
            (358, 27, 'Huyện Thanh Hà', 'Huyen-Thanh-Ha', 10),
            (359, 27, 'Huyện Kim Thành', 'Huyen-Kim-Thanh', 11),
            (360, 27, 'Huyện Bình Giang', 'Huyen-Binh-Giang', 12),
            (361, 31, 'Thị xã Hưng Yên', 'Thi-xa-Hung-Yen', 1),
            (362, 31, 'Huyện Kim Động', 'Huyen-Kim-Dong', 2),
            (363, 31, 'Huyện Ân Thi', 'Huyen-An-Thi', 3),
            (364, 31, 'Huyện Khoái Châu', 'Huyen-Khoai-Chau', 4),
            (365, 31, 'Huyện Yên Mỹ', 'Huyen-Yen-My', 5),
            (366, 31, 'Huyện Tiên Lữ', 'Huyen-Tien-Lu', 6),
            (367, 31, 'Huyện Phù Cừ', 'Huyen-Phu-Cu', 7),
            (368, 31, 'Huyện Mỹ Hào', 'Huyen-My-Hao', 8),
            (369, 31, 'Huyện Văn Lâm', 'Huyen-Van-Lam', 9),
            (370, 31, 'Huyện Văn Giang', 'Huyen-Van-Giang', 10),
            (371, 30, 'Thành phố Hoà Bình', 'Thanh-pho-Hoa-Binh', 1),
            (372, 30, 'Huyện Đà Bắc', 'Huyen-Da-Bac', 2),
            (373, 30, 'Huyện Mai Châu', 'Huyen-Mai-Chau', 3),
            (374, 30, 'Huyện Tân Lạc', 'Huyen-Tan-Lac', 4),
            (375, 30, 'Huyện Lạc Sơn', 'Huyen-Lac-Son', 5),
            (376, 30, 'Huyện Kỳ Sơn', 'Huyen-Ky-Son', 6),
            (377, 30, 'Huyện Lương Sơn', 'Huyen-Luong-Son', 7),
            (378, 30, 'Huyện Kim Bôi', 'Huyen-Kim-Boi', 8),
            (379, 30, 'Huyện Lạc Thuỷ', 'Huyen-Lac-Thuy', 9),
            (380, 30, 'Huyện Yên Thuỷ', 'Huyen-Yen-Thuy', 10),
            (381, 30, 'Huyện Cao Phong', 'Huyen-Cao-Phong', 11),
            (382, 25, 'Thành phố Phủ Lý', 'Thanh-pho-Phu-Ly', 1),
            (383, 25, 'Huyện Duy Tiên', 'Huyen-Duy-Tien', 2),
            (384, 25, 'Huyện Kim Bảng', 'Huyen-Kim-Bang', 3),
            (385, 25, 'Huyện Lý Nhân', 'Huyen-Ly-Nhan', 4),
            (386, 25, 'Huỵện Thanh Liêm', 'Huyen-Thanh-Liem', 5),
            (387, 25, 'Huyện Bình Lục', 'Huyen-Binh-Luc', 6),
            (388, 40, 'TP. Nam Định', 'TP-Nam-Dinh', 1),
            (389, 40, 'Huyện Mỹ Lộc', 'Huyen-My-Loc', 2),
            (390, 40, 'Huyện Xuân Trường', 'Huyen-Xuan-Truong', 3),
            (391, 40, 'Huyện Giao Thủy', 'Huyen-Giao-Thuy', 4),
            (392, 40, 'Huyện ý Yên', 'Huyen-y-Yen', 5),
            (393, 40, 'Huyện Vụ Bản', 'Huyen-Vu-Ban', 6),
            (394, 40, 'Huyện Nam Trực', 'Huyen-Nam-Truc', 7),
            (395, 40, 'Huyện Trực Ninh', 'Huyen-Truc-Ninh', 8),
            (396, 40, 'Huyện Nghĩa Hưng', 'Huyen-Nghia-Hung', 9),
            (397, 40, 'Huyện Hải Hậu', 'Huyen-Hai-Hau', 10),
            (398, 54, 'Thành phố Thái Bình', 'Thanh-pho-Thai-Binh', 1),
            (399, 54, 'Huyện Quỳnh Phụ', 'Huyen-Quynh-Phu', 2),
            (400, 54, 'Huyện Hưng Hà', 'Huyen-Hung-Ha', 3),
            (401, 54, 'Huyện Đông Hưng', 'Huyen-Dong-Hung', 4),
            (402, 54, 'Huyện Vũ Thư', 'Huyen-Vu-Thu', 5),
            (403, 54, 'Huyện Kiến Xương', 'Huyen-Kien-Xuong', 6),
            (404, 54, 'Huyện Tiền Hải', 'Huyen-Tien-Hai', 7),
            (405, 54, 'Huyện Thái Thuỵ', 'Huyen-Thai-Thuy', 8),
            (406, 42, 'Thành phố Ninh Bình', 'Thanh-pho-Ninh-Binh', 1),
            (407, 42, 'Thị xã Tam Điệp', 'Thi-xa-Tam-Diep', 2),
            (408, 42, 'Huyện Nho Quan', 'Huyen-Nho-Quan', 3),
            (409, 42, 'Huyện Gia Viễn', 'Huyen-Gia-Vien', 4),
            (410, 42, 'Huyện Hoa Lư', 'Huyen-Hoa-Lu', 5),
            (411, 42, 'Huyện Yên Mô', 'Huyen-Yen-Mo', 6),
            (412, 42, 'Huyện Kim Sơn', 'Huyen-Kim-Son', 7),
            (413, 42, 'Huyện Yên Khánh', 'Huyen-Yen-Khanh', 8),
            (414, 56, 'TP.Thanh Hoá', 'TPThanh-Hoa', 1),
            (415, 56, 'Thị xã Bỉm Sơn', 'Thi-xa-Bim-Son', 2),
            (416, 56, 'Thị xã Sầm Sơn', 'Thi-xa-Sam-Son', 3),
            (417, 56, 'Huyện Quan Hoá', 'Huyen-Quan-Hoa', 4),
            (418, 56, 'Huyện Quan Sơn', 'Huyen-Quan-Son', 5),
            (419, 56, 'Huyện Mường Lát', 'Huyen-Muong-Lat', 6),
            (420, 56, 'Huyện Bá Thước', 'Huyen-Ba-Thuoc', 7),
            (421, 56, 'Huyện Thường Xuân', 'Huyen-Thuong-Xuan', 8),
            (422, 56, 'Huyện Như Xuân', 'Huyen-Nhu-Xuan', 9),
            (423, 56, 'Huyện Như Thanh', 'Huyen-Nhu-Thanh', 10),
            (424, 56, 'Huyện Lang Chánh', 'Huyen-Lang-Chanh', 11),
            (425, 56, 'Huyện Ngọc Lặc', 'Huyen-Ngoc-Lac', 12),
            (426, 56, 'Huyện Thạch Thành', 'Huyen-Thach-Thanh', 13),
            (427, 56, 'Huyện Cẩm Thủy', 'Huyen-Cam-Thuy', 14),
            (428, 56, 'Huyện Thọ Xuân', 'Huyen-Tho-Xuan', 15),
            (429, 56, 'Huyện Vĩnh Lộc', 'Huyen-Vinh-Loc', 16),
            (430, 56, 'Huyện Thiệu Hoá', 'Huyen-Thieu-Hoa', 17),
            (431, 56, 'Huyện Triệu Sơn', 'Huyen-Trieu-Son', 18),
            (432, 56, 'Huyện Nông Cống', 'Huyen-Nong-Cong', 19),
            (433, 56, 'Huyện Đông Sơn', 'Huyen-Dong-Son', 20),
            (434, 56, 'Huyện Hà Trung', 'Huyen-Ha-Trung', 21),
            (435, 56, 'Huyện Hoằng Hoá', 'Huyen-Hoang-Hoa', 22),
            (436, 56, 'Huyện Nga Sơn', 'Huyen-Nga-Son', 23),
            (437, 56, 'Huyện Hậu Lộc', 'Huyen-Hau-Loc', 24),
            (438, 56, 'Huyện Quảng Xương', 'Huyen-Quang-Xuong', 25),
            (439, 56, 'Huyện Tĩnh Gia', 'Huyen-Tinh-Gia', 26),
            (440, 56, 'Huyện Yên Định', 'Huyen-Yen-Dinh', 27),
            (441, 41, 'Thành phố Vinh', 'Thanh-pho-Vinh', 1),
            (442, 41, 'Thị xã Cửa Lò', 'Thi-xa-Cua-Lo', 2),
            (443, 41, 'Huyện Quỳ Châu', 'Huyen-Quy-Chau', 3),
            (444, 41, 'Huyện Quỳ Hợp', 'Huyen-Quy-Hop', 4),
            (445, 41, 'Huyện Nghĩa Đàn', 'Huyen-Nghia-Dan', 5),
            (446, 41, 'Huyện Quỳnh Lưu', 'Huyen-Quynh-Luu', 6),
            (447, 41, 'Huyện Kỳ Sơn', 'Huyen-Ky-Son', 7),
            (448, 41, 'Huyện Tương Dương', 'Huyen-Tuong-Duong', 8),
            (449, 41, 'Huyện Con Cuông', 'Huyen-Con-Cuong', 9),
            (450, 41, 'Huyện Tân Kỳ', 'Huyen-Tan-Ky', 10),
            (451, 41, 'Huyện Yên Thành', 'Huyen-Yen-Thanh', 11),
            (452, 41, 'Huyện Diễn Châu', 'Huyen-Dien-Chau', 12),
            (453, 41, 'Huyện Anh Sơn', 'Huyen-Anh-Son', 13),
            (454, 41, 'Huyện Đô Lương', 'Huyen-Do-Luong', 14),
            (455, 41, 'Huyện Thanh Chương', 'Huyen-Thanh-Chuong', 15),
            (456, 41, 'Huyện Nghi Lộc', 'Huyen-Nghi-Loc', 16),
            (457, 41, 'Huyện Nam Đàn', 'Huyen-Nam-Dan', 17),
            (458, 41, 'Huyện Hưng Nguyên', 'Huyen-Hung-Nguyen', 18),
            (459, 41, 'Huyện Quế Phong', 'Huyen-Que-Phong', 19),
            (460, 26, 'Thành phố Hà Tĩnh', 'Thanh-pho-Ha-Tinh', 1),
            (461, 26, 'Thị xã Hồng Lĩnh', 'Thi-xa-Hong-Linh', 2),
            (462, 26, 'Huyện Hương Sơn', 'Huyen-Huong-Son', 3),
            (463, 26, 'Huyện Đức Thọ', 'Huyen-Duc-Tho', 4),
            (464, 26, 'Huyện Nghi Xuân', 'Huyen-Nghi-Xuan', 5),
            (465, 26, 'Huyện Can Lộc', 'Huyen-Can-Loc', 6),
            (466, 26, 'Huyện Hương Khê', 'Huyen-Huong-Khe', 7),
            (467, 26, 'Huyện Thạch Hà', 'Huyen-Thach-Ha', 8),
            (468, 26, 'Huyện Cẩm Xuyên', 'Huyen-Cam-Xuyen', 9),
            (469, 26, 'Huyện Kỳ Anh', 'Huyen-Ky-Anh', 10),
            (470, 26, 'Huyện Vũ Quang', 'Huyen-Vu-Quang', 11),
            (471, 26, 'Huyện Lộc Hà', 'Huyen-Loc-Ha', 12),
            (472, 46, 'Thành phố Đồng Hới', 'Thanh-pho-Dong-Hoi', 1),
            (473, 46, 'Huyện Tuyên Hoá', 'Huyen-Tuyen-Hoa', 2),
            (474, 46, 'Huyện Minh Hoá', 'Huyen-Minh-Hoa', 3),
            (475, 46, 'Huyện Quảng Trạch', 'Huyen-Quang-Trach', 4),
            (476, 46, 'Huyện Bố Trạch', 'Huyen-Bo-Trach', 5),
            (477, 46, 'Huyện Quảng Ninh', 'Huyen-Quang-Ninh', 6),
            (478, 46, 'Huyện Lệ Thuỷ', 'Huyen-Le-Thuy', 7),
            (479, 50, 'Thị xã Đông Hà', 'Thi-xa-Dong-Ha', 1),
            (480, 50, 'Thị xã Quảng Trị', 'Thi-xa-Quang-Tri', 2),
            (481, 50, 'Huyện Vĩnh Linh', 'Huyen-Vinh-Linh', 3),
            (482, 50, 'Huyện Gio Linh', 'Huyen-Gio-Linh', 4),
            (483, 50, 'Huyện Cam Lộ', 'Huyen-Cam-Lo', 5),
            (484, 50, 'Huyện Triệu Phong', 'Huyen-Trieu-Phong', 6),
            (485, 50, 'Huyện Hải Lăng', 'Huyen-Hai-Lang', 7),
            (486, 50, 'Huyện Hướng Hoá', 'Huyen-Huong-Hoa', 8),
            (487, 50, 'Huyện Đăk Rông', 'Huyen-Dak-Rong', 9),
            (488, 50, 'Huyện đảo Cồn cỏ', 'Huyen-dao-Con-co', 10),
            (489, 57, 'Thành phố Huế', 'Thanh-pho-Hue', 1),
            (490, 57, 'Huyện Phong Điền', 'Huyen-Phong-Dien', 2),
            (491, 57, 'Huyện Hương Trà', 'Huyen-Huong-Tra', 3),
            (492, 57, 'Huyện Phú Vang', 'Huyen-Phu-Vang', 4),
            (493, 57, 'Huyện Hương Thuỷ', 'Huyen-Huong-Thuy', 5),
            (494, 57, 'Huyện Nam Đông', 'Huyen-Nam-Dong', 6),
            (495, 57, 'Huyện A Lưới', 'Huyen-A-Luoi', 7),
            (496, 57, 'Huyện Quảng Điền', 'Huyen-Quang-Dien', 8),
            (497, 57, 'Huyện Phú Lộc', 'Huyen-Phu-Loc', 9),
            (498, 47, 'Thành phố Tam Kỳ', 'Thanh-pho-Tam-Ky', 1),
            (499, 47, 'Thị xã Hội An', 'Thi-xa-Hoi-An', 2),
            (500, 47, 'Huyện Duy Xuyên', 'Huyen-Duy-Xuyen', 3),
            (501, 47, 'Huyện Điện Bàn', 'Huyen-Dien-Ban', 4),
            (502, 47, 'Huyện Đại Lộc', 'Huyen-Dai-Loc', 5),
            (503, 47, 'Huyện Quế Sơn', 'Huyen-Que-Son', 6),
            (504, 47, 'Huyện Hiệp Đức', 'Huyen-Hiep-Duc', 7),
            (505, 47, 'Huyện Thăng Bình', 'Huyen-Thang-Binh', 8),
            (506, 47, 'Huyện Núi Thành', 'Huyen-Nui-Thanh', 9),
            (507, 47, 'Huyện Tiên Phước', 'Huyen-Tien-Phuoc', 10),
            (508, 47, 'Huyện Bắc Trà My', 'Huyen-Bac-Tra-My', 11),
            (509, 47, 'Huyện Đông Giang', 'Huyen-Dong-Giang', 12),
            (510, 47, 'Huyện Nam Giang', 'Huyen-Nam-Giang', 13),
            (511, 47, 'Huyện Phước Sơn', 'Huyen-Phuoc-Son', 14),
            (512, 47, 'Huyện Nam Trà My', 'Huyen-Nam-Tra-My', 15),
            (513, 47, 'Huyện Tây Giang', 'Huyen-Tay-Giang', 16),
            (514, 47, 'Huyện Phú Ninh', 'Huyen-Phu-Ninh', 17),
            (515, 47, 'Huyện Nông Sơn&#039;', 'Huyen-Nong-Son', 18),
            (516, 48, 'TP.Quảng Ngãi', 'TPQuang-Ngai', 1),
            (517, 48, 'Huyện Lý Sơn', 'Huyen-Ly-Son', 2),
            (518, 48, 'Huyện Bình Sơn', 'Huyen-Binh-Son', 3),
            (519, 48, 'Huyện Trà Bồng', 'Huyen-Tra-Bong', 4),
            (520, 48, 'Huyện Sơn Tịnh', 'Huyen-Son-Tinh', 5),
            (521, 48, 'Huyện Sơn Hà', 'Huyen-Son-Ha', 6),
            (522, 48, 'Huyện Tư Nghĩa', 'Huyen-Tu-Nghia', 7),
            (523, 48, 'Huyện Nghĩa Hành', 'Huyen-Nghia-Hanh', 8),
            (524, 48, 'Huyện Minh Long', 'Huyen-Minh-Long', 9),
            (525, 48, 'Huyện Mộ Đức', 'Huyen-Mo-Duc', 10),
            (526, 48, 'Huyện Đức Phổ', 'Huyen-Duc-Pho', 11),
            (527, 48, 'Huyện Ba Tơ', 'Huyen-Ba-To', 12),
            (528, 48, 'Huyện Sơn Tây', 'Huyen-Son-Tay', 13),
            (529, 48, 'Huyện Tây Trà', 'Huyen-Tay-Tra', 14),
            (530, 34, 'Thị xã KonTum', 'Thi-xa-KonTum', 1),
            (531, 34, 'Huyện Đăk Glei', 'Huyen-Dak-Glei', 2),
            (532, 34, 'Huyện Ngọc Hồi', 'Huyen-Ngoc-Hoi', 3),
            (533, 34, 'Huyện Đăk Tô', 'Huyen-Dak-To', 4),
            (534, 34, 'Huyện Sa Thầy', 'Huyen-Sa-Thay', 5),
            (535, 34, 'Huyện Kon Plong', 'Huyen-Kon-Plong', 6),
            (536, 34, 'Huyện Đăk Hà', 'Huyen-Dak-Ha', 7),
            (537, 34, 'Huyện Kon Rộy', 'Huyen-Kon-Roy', 8),
            (538, 34, 'Huyện Tu Mơ Rông', 'Huyen-Tu-Mo-Rong', 9),
            (539, 10, 'Thành phố Quy Nhơn', 'Thanh-pho-Quy-Nhon', 1),
            (540, 10, 'Huyện An Lão', 'Huyen-An-Lao', 2),
            (541, 10, 'Huyện Hoài Ân', 'Huyen-Hoai-An', 3),
            (542, 10, 'Huyện Hoài Nhơn', 'Huyen-Hoai-Nhon', 4),
            (543, 10, 'Huyện Phù Mỹ', 'Huyen-Phu-My', 5),
            (544, 10, 'Huyện Phù Cát', 'Huyen-Phu-Cat', 6),
            (545, 10, 'Huyện Vĩnh Thạnh', 'Huyen-Vinh-Thanh', 7),
            (546, 10, 'Huyện Tây Sơn', 'Huyen-Tay-Son', 8),
            (547, 10, 'Huyện Vân Canh', 'Huyen-Van-Canh', 9),
            (548, 10, 'Huyện An Nhơn', 'Huyen-An-Nhon', 10),
            (549, 10, 'Huyện Tuy Phước', 'Huyen-Tuy-Phuoc', 11),
            (550, 53, 'Thị xã Tây Ninh', 'Thi-xa-Tay-Ninh', 1),
            (551, 53, 'Huyện Tân Biên', 'Huyen-Tan-Bien', 2),
            (552, 53, 'Huyện Tân Châu', 'Huyen-Tan-Chau', 3),
            (553, 53, 'Huyện Dương Minh Châu', 'Huyen-Duong-Minh-Chau', 4),
            (554, 53, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 5),
            (555, 53, 'Huyện Hoà Thành', 'Huyen-Hoa-Thanh', 6),
            (556, 53, 'Huyện Bến Cầu', 'Huyen-Ben-Cau', 7),
            (557, 53, 'Huyện Gò Dầu', 'Huyen-Go-Dau', 8),
            (558, 53, 'Huyện Trảng Bàng', 'Huyen-Trang-Bang', 9),
            (559, 45, 'Thị xã Tuy Hoà', 'Thi-xa-Tuy-Hoa', 1),
            (560, 45, 'Huyện Đồng Xuân', 'Huyen-Dong-Xuan', 2),
            (561, 45, 'Huyện Sông Cầu', 'Huyen-Song-Cau', 3),
            (562, 45, 'Huyện Tuy An', 'Huyen-Tuy-An', 4),
            (563, 45, 'Huyện Sơn Hoà', 'Huyen-Son-Hoa', 5),
            (564, 45, 'Huyện Sông Hinh', 'Huyen-Song-Hinh', 6),
            (565, 45, 'Huyện Đông Hoà', 'Huyen-Dong-Hoa', 7),
            (566, 45, 'Huyện Phú Hoà', 'Huyen-Phu-Hoa', 8),
            (567, 45, 'Huyện Tây Hoà', 'Huyen-Tay-Hoa', 9),
            (568, 13, 'Thành phố Phan Thiết', 'Thanh-pho-Phan-Thiet', 1),
            (569, 13, 'Huyện Tuy Phong', 'Huyen-Tuy-Phong', 2),
            (570, 13, 'Huyện Bắc Bình', 'Huyen-Bac-Binh', 3),
            (571, 13, 'Huyện Hàm Thuận Bắc', 'Huyen-Ham-Thuan-Bac', 4),
            (572, 13, 'Huyện Hàm Thuận Nam', 'Huyen-Ham-Thuan-Nam', 5),
            (573, 13, 'Huyện Hàm Tân', 'Huyen-Ham-Tan', 6),
            (574, 13, 'Huyện Đức Linh', 'Huyen-Duc-Linh', 7),
            (575, 13, 'Huyện Tánh Linh', 'Huyen-Tanh-Linh', 8),
            (576, 13, 'Huyện đảo Phú Quý', 'Huyen-dao-Phu-Quy', 9),
            (577, 13, 'Thị xã LaGi', 'Thi-xa-LaGi', 10),
            (578, 21, 'Thành phố Biên Hoà', 'Thanh-pho-Bien-Hoa', 1),
            (579, 21, 'Huyện Vĩnh Cửu', 'Huyen-Vinh-Cuu', 2),
            (580, 21, 'Huyện Tân Phú', 'Huyen-Tan-Phu', 3),
            (581, 21, 'Huyện Định Quán', 'Huyen-Dinh-Quan', 4),
            (582, 21, 'Huyện Thống Nhất', 'Huyen-Thong-Nhat', 5),
            (583, 21, 'Thị xã Long Khánh', 'Thi-xa-Long-Khanh', 6),
            (584, 21, 'Huyện Xuân Lộc', 'Huyen-Xuan-Loc', 7),
            (585, 21, 'Huyện Long Thành', 'Huyen-Long-Thanh', 8),
            (586, 21, 'Huyện Nhơn Trạch', 'Huyen-Nhon-Trach', 9),
            (587, 21, 'Huyện Trảng Bom', 'Huyen-Trang-Bom', 10),
            (588, 21, 'Huyện Cẩm Mỹ', 'Huyen-Cam-My', 11),
            (589, 39, 'Thị xã Tân An', 'Thi-xa-Tan-An', 1),
            (590, 39, 'Huyện Vĩnh Hưng', 'Huyen-Vinh-Hung', 2),
            (591, 39, 'Huyện Mộc Hoá', 'Huyen-Moc-Hoa', 3),
            (592, 39, 'Huyện Tân Thạnh', 'Huyen-Tan-Thanh', 4),
            (593, 39, 'Huyện Thạnh Hoá', 'Huyen-Thanh-Hoa', 5),
            (594, 39, 'Huyện Đức Huệ', 'Huyen-Duc-Hue', 6),
            (595, 39, 'Huyện Đức Hoà&#039;', 'Huyen-Duc-Hoa', 7),
            (596, 39, 'Huyện Bến Lức', 'Huyen-Ben-Luc', 8),
            (597, 39, 'Huyện Thủ Thừa', 'Huyen-Thu-Thua', 9),
            (598, 39, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 10),
            (599, 39, 'Huyện Tân Trụ', 'Huyen-Tan-Tru', 11),
            (600, 39, 'Huyện Cần Đước', 'Huyen-Can-Duoc', 12),
            (601, 39, 'Huyện Cần Giuộc', 'Huyen-Can-Giuoc', 13),
            (602, 39, 'Huyện Tân Hưng&#039;', 'Huyen-Tan-Hung', 14),
            (603, 22, 'Thành phố Cao Lãnh', 'Thanh-pho-Cao-Lanh', 1),
            (604, 22, 'Thị xã Sa Đéc', 'Thi-xa-Sa-Dec', 2),
            (605, 22, 'Huyện Tân Hồng', 'Huyen-Tan-Hong', 3),
            (606, 22, 'Huyện Hồng Ngự', 'Huyen-Hong-Ngu', 4),
            (607, 22, 'Huyện Tam Nông', 'Huyen-Tam-Nong', 5),
            (608, 22, 'Huyện Thanh Bình', 'Huyen-Thanh-Binh', 6),
            (609, 22, 'Huyện Cao Lãnh', 'Huyen-Cao-Lanh', 7),
            (610, 22, 'Huyện Lấp Vò', 'Huyen-Lap-Vo', 8),
            (611, 22, 'Huyện Tháp Mười', 'Huyen-Thap-Muoi', 9),
            (612, 22, 'Huyện Lai Vung', 'Huyen-Lai-Vung', 10),
            (613, 22, 'Huyện Châu Thành', 'Huyen-Chau-Thanh', 11),
            (614, 11, 'Thị xã Thủ Dầu Một', 'Thi-xa-Thu-Dau-Mot', 1),
            (615, 11, 'Huyện Bến Cát', 'Huyen-Ben-Cat', 2),
            (616, 11, 'Huyện Tân Uyên', 'Huyen-Tan-Uyen', 3),
            (617, 11, 'Huyện Thuận An', 'Huyen-Thuan-An', 4),
            (618, 11, 'Huyện Dĩ An', 'Huyen-Di-An', 5),
            (619, 11, 'Huyện Phú Giáo', 'Huyen-Phu-Giao', 6),
            (620, 11, 'Huyện Dầu Tiếng', 'Huyen-Dau-Tieng', 7),
            (621, 12, 'Thị xã Đồng Xoài', 'Thi-xa-Dong-Xoai', 1),
            (622, 12, 'Huyện Đồng Phú', 'Huyen-Dong-Phu', 2),
            (623, 12, 'Huyện Chơn Thành', 'Huyen-Chon-Thanh', 3),
            (624, 12, 'Huyện Bình Long', 'Huyen-Binh-Long', 4),
            (625, 12, 'Huyện Lộc Ninh', 'Huyen-Loc-Ninh', 5),
            (626, 12, 'Huyện Bù Đốp', 'Huyen-Bu-Dop', 6),
            (627, 12, 'Huyện Phước Long', 'Huyen-Phuoc-Long', 7),
            (628, 12, 'Huyện Bù Đăng', 'Huyen-Bu-Dang', 8),
            (630, 43, 'TP.Phan Rang - Tháp Chàm', 'TPPhan-Rang-Thap-Cham', 1),
            (631, 43, 'Huyện Ninh Sơn', 'Huyen-Ninh-Son', 2),
            (632, 43, 'Huyện Ninh Hải', 'Huyen-Ninh-Hai', 3),
            (633, 43, 'Huyện Ninh Phước', 'Huyen-Ninh-Phuoc', 4),
            (634, 43, 'Huyện Bác ái', 'Huyen-Bac-ai', 5),
            (635, 43, 'Huyện Thuận Bắc', 'Huyen-Thuan-Bac', 6),
            (636, 23, 'Thành phố Pleiku', 'Thanh-pho-Pleiku', 1),
            (637, 23, 'Huyện Chư Păh', 'Huyen-Chu-Pah', 2),
            (638, 23, 'Huyện Mang Yang', 'Huyen-Mang-Yang', 3),
            (639, 23, 'Huyện Kbang', 'Huyen-Kbang', 4),
            (640, 23, 'Thị xã An Khê', 'Thi-xa-An-Khe', 5),
            (641, 23, 'Huyện Kông Chro', 'Huyen-Kong-Chro', 6),
            (642, 23, 'Huyện Đức Cơ', 'Huyen-Duc-Co', 7),
            (643, 23, 'Huyện Chưprông', 'Huyen-Chuprong', 8),
            (644, 23, 'Huyện Chư Sê', 'Huyen-Chu-Se', 9),
            (645, 23, 'Huyện Ayunpa', 'Huyen-Ayunpa', 10),
            (646, 23, 'Huyện Krông Pa', 'Huyen-Krong-Pa', 11),
            (647, 23, 'Huyện Ia Grai', 'Huyen-Ia-Grai', 12),
            (648, 23, 'Huyện Đăk Đoa', 'Huyen-Dak-Doa', 13),
            (649, 23, 'Huyện Ia Pa', 'Huyen-Ia-Pa', 14),
            (650, 23, 'Huyện Đăk Pơ', 'Huyen-Dak-Po', 15),
            (651, 23, 'Huyện Phú Thiện', 'Huyen-Phu-Thien', 16),
            (652, 32, 'Thành phố Nha Trang', 'Thanh-pho-Nha-Trang', 1),
            (653, 32, 'Huyện Vạn Ninh', 'Huyen-Van-Ninh', 2),
            (654, 32, 'Huyện Ninh Hoà', 'Huyen-Ninh-Hoa', 3),
            (655, 32, 'Huyện Diên Khánh', 'Huyen-Dien-Khanh', 4),
            (656, 32, 'Huyện Khánh Vĩnh', 'Huyen-Khanh-Vinh', 5),
            (657, 32, 'Thị xã Cam Ranh', 'Thi-xa-Cam-Ranh', 6),
            (658, 32, 'Huyện Khánh Sơn', 'Huyen-Khanh-Son', 7),
            (659, 32, 'Huyện Trường Sa', 'Huyen-Truong-Sa', 8),
            (660, 32, 'Huyện Cam Lâm', 'Huyen-Cam-Lam', 9),
            (661, 36, 'Thành phố Đà Lạt', 'Thanh-pho-Da-Lat', 1),
            (662, 36, 'Thị xã Bảo Lộc', 'Thi-xa-Bao-Loc', 2),
            (663, 36, 'Huyện Đức Trọng', 'Huyen-Duc-Trong', 3),
            (664, 36, 'Huyện Di Linh', 'Huyen-Di-Linh', 4),
            (665, 36, 'Huyện Đơn Dương', 'Huyen-Don-Duong', 5),
            (666, 36, 'Huyện Lạc Dương', 'Huyen-Lac-Duong', 6),
            (667, 36, 'Huyện Đạ Huoai', 'Huyen-Da-Huoai', 7),
            (668, 36, 'Huyện Đạ Tẻh', 'Huyen-Da-Teh', 8),
            (669, 36, 'Huyện Cát Tiên', 'Huyen-Cat-Tien', 9),
            (670, 36, 'Huyện Lâm Hà', 'Huyen-Lam-Ha', 10),
            (671, 36, 'Huyện Bảo Lâm', 'Huyen-Bao-Lam', 11),
            (672, 36, 'Huyện Đam Rông', 'Huyen-Dam-Rong', 12),
            (675, 18, 'TP.Buôn Ma Thuột', 'TPBuon-Ma-Thuot', 1),
            (676, 18, 'Huyện Ea H Leo', 'Huyen-Ea-H-Leo', 2),
            (677, 18, 'Huyện Krông Buk', 'Huyen-Krong-Buk', 3),
            (678, 18, 'Huyện Krông Năng', 'Huyen-Krong-Nang', 4),
            (679, 18, 'Huyện Ea Súp', 'Huyen-Ea-Sup', 5),
            (680, 18, 'Huyện Cư M gar', 'Huyen-Cu-M-gar', 6),
            (681, 18, 'Huyện Krông Pắc', 'Huyen-Krong-Pac', 7),
            (682, 18, 'Huyện Ea Kar', 'Huyen-Ea-Kar', 8),
            (683, 18, 'Huyện M&#039;&#039;Đrăk', 'Huyen-M-Drak', 9),
            (684, 18, 'Huyện Krông Ana', 'Huyen-Krong-Ana', 10),
            (685, 18, 'Huyện Krông Bông', 'Huyen-Krong-Bong', 11),
            (686, 18, 'Huyện Lăk', 'Huyen-Lak', 12),
            (687, 18, 'Huyện Buôn Đôn', 'Huyen-Buon-Don', 13),
            (688, 18, 'Huyện Cư Kuin', 'Huyen-Cu-Kuin', 14)");
    }
}
